printWidth: 90
tabWidth: 2
useTabs: true
semi: true
singleQuote: true
jsxSingleQuote: true
quoteProps: as-needed
trailingComma: all
bracketSpacing: false
bracketSameLine: false
jsxBracketSameLine: false
arrowParens: avoid
endOfLine: 'lf'
singleAttributePerLine: true
