arrowParens: avoid
bracketSpacing: true
bracketSameLine: false
endOfLine: lf
jsxBracketSameLine: false
jsxSingleQuote: true
printWidth: 90
quoteProps: as-needed
semi: true
singleAttributePerLine: true
singleQuote: true
tabWidth: 2
trailingComma: es5
useTabs: true
